spring:
  application:
    name: vaier
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /**

server:
  port: 8080
  address: 0.0.0.0

logging:
  level:
    net.vaier: DEBUG
    org.springframework: INFO

wireguard:
  server:
    endpoint: vaier.net:51820