spring:
  application:
    name: wireweave

server:
  port: 8080
  address: 0.0.0.0

logging:
  level:
    com.wireweave: DEBUG
    org.springframework: INFO

wireguard:
  server:
    endpoint: wireguard.eilertsen.family:51820