package net.vaier.domain;

import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class PeerIdTest {

    @Test
    void sanitized_keepsAlreadyValidName() {
        assertThat(PeerId.sanitized("media-server_01").value()).isEqualTo("media-server_01");
    }

    @Test
    void sanitized_replacesInvalidCharactersWithHyphen() {
        assertThat(PeerId.sanitized("media server!!").value()).isEqualTo("media-server");
    }

    @Test
    void sanitized_collapsesRepeatedHyphens() {
        assertThat(PeerId.sanitized("a   b").value()).isEqualTo("a-b");
    }

    @Test
    void sanitized_stripsLeadingAndTrailingHyphens() {
        assertThat(PeerId.sanitized("  -nas-  ").value()).isEqualTo("nas");
    }

    @Test
    void sanitized_preservesCase() {
        assertThat(PeerId.sanitized("Media Server").value()).isEqualTo("Media-Server");
    }

    @Test
    void sanitized_throwsWhenInputIsNull() {
        assertThatThrownBy(() -> PeerId.sanitized(null))
            .isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    void sanitized_throwsWhenInputSanitisesToNothing() {
        assertThatThrownBy(() -> PeerId.sanitized("!!!"))
            .isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    void constructor_rejectsBlankValue() {
        assertThatThrownBy(() -> new PeerId("   "))
            .isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    void isSameAs_trueOnlyForIdenticalId() {
        PeerId id = PeerId.sanitized("nas");
        assertThat(id.isSameAs("nas")).isTrue();
        assertThat(id.isSameAs("nas2")).isFalse();
    }

    @Test
    void generate_returnsBareSlugWhenUnused() {
        assertThat(PeerId.generate("Media Server", Set.of()).value()).isEqualTo("Media-Server");
    }

    @Test
    void generate_appendsNumericSuffixWhenSlugIsTaken() {
        assertThat(PeerId.generate("Media Server", Set.of("Media-Server")).value())
            .isEqualTo("Media-Server-2");
    }

    @Test
    void generate_skipsPastConsecutiveTakenSuffixes() {
        assertThat(PeerId.generate("Media Server",
                List.of("Media-Server", "Media-Server-2", "Media-Server-3")).value())
            .isEqualTo("Media-Server-4");
    }

    @Test
    void generate_toleratesNullExistingIds() {
        assertThat(PeerId.generate("nas", null).value()).isEqualTo("nas");
    }

    @Test
    void generate_throwsWhenInputSanitisesToNothing() {
        assertThatThrownBy(() -> PeerId.generate("!!!", Set.of()))
            .isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    void display_rendersAutoGeneratedHyphensAsSpaces() {
        assertThat(PeerId.display("media-server")).isEqualTo("media server");
        assertThat(PeerId.sanitized("Media Server").display()).isEqualTo("Media Server");
    }

    @Test
    void display_leavesNamesWithoutHyphensUntouched() {
        assertThat(PeerId.display("nas")).isEqualTo("nas");
    }

    @Test
    void display_nullSafe() {
        assertThat(PeerId.display(null)).isNull();
    }
}
