package net.vaier.domain;

import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class PeerIdTest {

    @Test
    void sanitized_normalisesToTheAllowedCharset() {
        record Row(String description, String input, String expected) {}
        List<Row> rows = List.of(
            new Row("keeps an already-valid name", "media-server_01", "media-server_01"),
            new Row("replaces invalid characters with a hyphen", "media server!!", "media-server"),
            new Row("collapses repeated hyphens", "a   b", "a-b"),
            new Row("strips leading and trailing hyphens", "  -nas-  ", "nas"),
            new Row("preserves case", "Media Server", "Media-Server")
        );

        for (Row row : rows) {
            assertThat(PeerId.sanitized(row.input()).value()).as(row.description()).isEqualTo(row.expected());
        }
    }

    @Test
    void sanitized_throwsWhenInputIsNull() {
        assertThatThrownBy(() -> PeerId.sanitized(null))
            .isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    void sanitized_throwsWhenInputSanitisesToNothing() {
        assertThatThrownBy(() -> PeerId.sanitized("!!!"))
            .isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    void constructor_rejectsCharactersOutsideAllowedCharset() {
        record Row(String description, String input) {}
        List<Row> rows = List.of(
            new Row("blank value", "   "),
            new Row("path traversal sequence", "../etc"),
            new Row("slash", "a/b"),
            new Row("dot", "a.b"),
            new Row("space", "a b"),
            new Row("bang", "a!b")
        );

        for (Row row : rows) {
            assertThatThrownBy(() -> new PeerId(row.input())).as(row.description()).isInstanceOf(IllegalArgumentException.class);
        }
    }

    @Test
    void constructor_acceptsValidCharsetValues() {
        assertThat(new PeerId("Media-Server_01").value()).isEqualTo("Media-Server_01");
        assertThat(new PeerId("nas").value()).isEqualTo("nas");
    }

    @Test
    void isSameAs_trueOnlyForIdenticalId() {
        PeerId id = PeerId.sanitized("nas");
        assertThat(id.isSameAs("nas")).isTrue();
        assertThat(id.isSameAs("nas2")).isFalse();
    }

    @Test
    void generate_returnsBareSlugWhenUnused() {
        assertThat(PeerId.generate("Media Server", Set.of()).value()).isEqualTo("Media-Server");
    }

    @Test
    void generate_appendsNumericSuffixWhenSlugIsTaken() {
        assertThat(PeerId.generate("Media Server", Set.of("Media-Server")).value())
            .isEqualTo("Media-Server-2");
    }

    @Test
    void generate_skipsPastConsecutiveTakenSuffixes() {
        assertThat(PeerId.generate("Media Server",
                List.of("Media-Server", "Media-Server-2", "Media-Server-3")).value())
            .isEqualTo("Media-Server-4");
    }

    @Test
    void generate_toleratesNullExistingIds() {
        assertThat(PeerId.generate("nas", null).value()).isEqualTo("nas");
    }

    @Test
    void generate_throwsWhenInputSanitisesToNothing() {
        assertThatThrownBy(() -> PeerId.generate("!!!", Set.of()))
            .isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    void display_rendersAutoGeneratedHyphensAsSpaces() {
        assertThat(PeerId.display("media-server")).isEqualTo("media server");
        assertThat(PeerId.sanitized("Media Server").display()).isEqualTo("Media Server");
    }

    @Test
    void display_leavesNamesWithoutHyphensUntouched() {
        assertThat(PeerId.display("nas")).isEqualTo("nas");
    }

    @Test
    void display_nullSafe() {
        assertThat(PeerId.display(null)).isNull();
    }
}
